# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serialize.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fserialize.proto\"<\n\x04\x44\x61ta\x12\r\n\x05\x65mbed\x18\x01 \x03(\x01\x12\n\n\x02\x66n\x18\x02 \x03(\t\x12\x0c\n\x04name\x18\x03 \x03(\t\x12\x0b\n\x03\x64oc\x18\x04 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serialize_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATA']._serialized_start=19
  _globals['_DATA']._serialized_end=79
# @@protoc_insertion_point(module_scope)
